# ------------------------------------------------------------------
#  Deterministic cost / feasibility engine for 2-Echelon EVRP
# ------------------------------------------------------------------

from __future__ import annotations
import math
from dataclasses import dataclass, field
from typing import Dict, List, Tuple, Any


# ==================================================================
# 	Simple solution container
# ==================================================================
@dataclass
class Solution:
    """
    Very lean container holding
      lv_routes : List[List[str]]
          each sub-list is a complete LV tour  D … S … D
      ev_routes : Dict[ str , List[List[str]] ]
          key      = satellite-id
          value[i] = one EV tour that starts/ends at that satellite
                     (sat , … , sat)
    """
    lv_routes: List[List[str]] = field(default_factory=list)
    ev_routes: Dict[str, List[List[str]]] = field(default_factory=dict)

    # helper – iterate over *all* routes no matter the echelon
    def all_routes(self):
        for r in self.lv_routes:
            yield r
        for rlist in self.ev_routes.values():
            for r in rlist:
                yield r


# ==================================================================
# 	Evaluator
# ==================================================================
class Evaluator:
    """
    Parameters
    ----------
    instance : dict
        data generated by the Parser
    check_sat_inventory : bool, default True
        verify that goods delivered by LVs reach a satellite before EVs
        take them away (stock never negative).
    check_time_windows  : bool, default True
        enforce ReadyTime / DueDate at customer nodes.

    Remarks
    -------
    • Distance = straight-line Euclidean
    • Energy   = distance  (r = 1)
    • Charging : whenever an EV visits an 'f' node it is re-filled to 100 %
                 and the time penalty  (Q-soc)·g  is added.
    • The objective returned is *travel distance* (LV + EV); you can
      convert that to money outside if desired.
    """

    # ----------------------------------------------------------------
    def __init__(
        self,
        instance: Dict[str, Any],
        *,
        check_sat_inventory: bool = True,
        check_time_windows: bool = True,
    ) -> None:
        self.data = instance
        self.chk_stock = check_sat_inventory
        self.chk_tw    = check_time_windows

        p = instance["params"]
        self.LV_CAP   = p["L"]
        self.EV_CAP   = p["C"]
        self.BAT_CAP  = p["Q"]
        self.INV_G    = p["g"]      # inverse charging rate
        self.SPEED    = p["v"]

        # ------------------------------------------------------------
        # Pre-compute distance matrix  (all nodes)
        # ------------------------------------------------------------
        self.dist: Dict[str, Dict[str, float]] = {}
        coords = {i: (n["x"], n["y"]) for i, n in instance["nodes"].items()}
        for i, (xi, yi) in coords.items():
            row = {}
            for j, (xj, yj) in coords.items():
                row[j] = math.hypot(xi - xj, yi - yj)
            self.dist[i] = row

    # ----------------------------------------------------------------
    def evaluate(self, sol: Solution) -> Dict[str, Any]:
        """
        Returns
        -------
        dict( cost=float,
              feasible=bool,
              violations={'cap','battery','time','stock'} )
        """

        # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        # Pre-step: how much demand does each satellite have to ship?
        # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        demand_by_sat: Dict[str, float] = {}
        for s, routes in sol.ev_routes.items():
            total = 0.0
            for r in routes:
                for nid in r:
                    if self.data["nodes"][nid]["Type"] == "c":
                        total += self.data["nodes"][nid]["DeliveryDemand"]
            demand_by_sat[s] = total

        # store violations
        vio = dict(cap=0, battery=0, time=0, stock=0)
        cost = 0.0

        # ============================================================
        # 1)  FIRST ECHELON  (LVs)
        # ============================================================
        delivery_events: Dict[str, List[Tuple[float, float]]] = {}

        for route in sol.lv_routes:
            if not self._check_endpoints(route, want_type="d"):
                raise ValueError("LV route must start & end at a depot")

            load_truck = 0.0
            time = 0.0
            prev = route[0]

            for nxt in route[1:]:
                # travel
                d = self.dist[prev][nxt]
                cost += d
                time += d / self.SPEED
                prev = nxt

                # unloading at satellite
                if self.data["nodes"][nxt]["Type"] == "s":
                    qty = demand_by_sat.get(nxt, 0.0)
                    delivery_events.setdefault(nxt, []).append((time, qty))
                    load_truck += qty

            if load_truck > self.LV_CAP:
                vio["cap"] += 1

        # ============================================================
        # 2)  SECOND ECHELON  (EVs)
        # ============================================================
        pickup_events: Dict[str, List[Tuple[float, float]]] = {}

        for sat, routes in sol.ev_routes.items():
            if self.data["nodes"][sat]["Type"] != "s":
                raise ValueError(f"Key '{sat}' in ev_routes is not a satellite")

            for r in routes:
                if r[0] != sat or r[-1] != sat:
                    raise ValueError("Each EV route must start/end at its satellite")

                soc   = self.BAT_CAP
                load  = 0.0
                time  = 0.0
                prev  = sat

                # goods are taken from satellite *at departure*
                demand_this_route = self._route_delivery_demand(r)
                pickup_events.setdefault(sat, []).append((0.0, -demand_this_route))

                for nxt in r[1:]:
                    d  = self.dist[prev][nxt]
                    e  = d                          # because r = 1
                    tt = d / self.SPEED

                    time += tt
                    soc  -= e
                    if soc < 0:
                        vio["battery"] += 1

                    ntype = self.data["nodes"][nxt]["Type"]

                    if ntype == "f":               # charging stop
                        time += (self.BAT_CAP - soc) * self.INV_G
                        soc = self.BAT_CAP

                    elif ntype == "c":
                        node = self.data["nodes"][nxt]

                        # time windows?
                        if self.chk_tw:
                            if time < node["ReadyTime"]:
                                time = node["ReadyTime"]
                            if time > node["DueDate"]:
                                vio["time"] += 1

                        time += node["ServiceTime"]

                        load += node["DeliveryDemand"]
                        if load > self.EV_CAP:
                            vio["cap"] += 1

                    cost += d
                    prev = nxt

        # ============================================================
        # 3)  SATELLITE INVENTORY BALANCE
        # ============================================================
        if self.chk_stock:
            for s in self.data["satellites"]:
                events = delivery_events.get(s, []) + pickup_events.get(s, [])
                if not events:
                    continue
                events.sort(key=lambda x: x[0])     # chronological
                stock = 0.0
                for _, delta in events:
                    stock += delta
                    if stock < -1e-6:
                        vio["stock"] += 1
                        break

        feasible = not any(vio.values())
        return dict(cost=cost, feasible=feasible, violations=vio)

    # ----------------------------------------------------------------
    # helper functions
    # ----------------------------------------------------------------
    def _route_delivery_demand(self, r: List[str]) -> float:
        """Sum of DeliveryDemand of all customers in route"""
        tot = 0.0
        for nid in r:
            if self.data["nodes"][nid]["Type"] == "c":
                tot += self.data["nodes"][nid]["DeliveryDemand"]
        return tot

    @staticmethod
    def _check_endpoints(route: List[str], *, want_type: str) -> bool:
        return (
            len(route) >= 2
            and route[0] == route[-1]
            and route[0][0].lower() == want_type
        )
